# Complex test file for shell injection vulnerabilities
# This file contains complex shell injection patterns for comprehensive testing

name: Test Complex Shell Injection

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-complex-injections:
    runs-on: ubuntu-latest
    steps:
      - name: Test with conditional logic
        run: |
          if [ "${{ github.event.pull_request.title }}" = "test" ]; then
            echo "Title matches test"
          fi
        # This should trigger the run-shell-injection Semgrep rule

      - name: Test with command substitution
        run: |
          RESULT=$(echo "Title: ${{ github.event.pull_request.title }}")
          echo "$RESULT"
        # This should trigger the run-shell-injection Semgrep rule

      - name: Test with multiple variables
        run: |
          echo "PR: ${{ github.event.pull_request.title }}"
          echo "Issue: ${{ github.event.issue.title }}"
          echo "Comment: ${{ github.event.comment.body }}"
        # This should trigger multiple run-shell-injection Semgrep rules

      - name: Test with shell redirection
        run: |
          echo "Logging: ${{ github.event.pull_request.body }}" > /tmp/log.txt
          cat /tmp/log.txt
        # This should trigger the run-shell-injection Semgrep rule

      - name: Test with environment variable
        run: |
          export TITLE="${{ github.event.pull_request.title }}"
          echo "Exported title: $TITLE"
        # This should trigger the run-shell-injection Semgrep rule

  test-review-injections:
    runs-on: ubuntu-latest
    steps:
      - name: Test review body injection
        run: 'echo "Review: ${{ github.event.review.body }}"'
        # This should trigger the run-shell-injection Semgrep rule

      - name: Test review comment injection
        run: 'echo "Review comment: ${{ github.event.review_comment.body }}"'
        # This should trigger the run-shell-injection Semgrep rule

      - name: Test head label injection
        run: 'echo "Head label: ${{ github.event.pull_request.head.label }}"'
        # This should trigger the run-shell-injection Semgrep rule

      - name: Test default branch injection
        run: 'echo "Default branch: ${{ github.event.pull_request.head.repo.default_branch }}"'
        # This should trigger the run-shell-injection Semgrep rule
