name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings as comments on pull requests.
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep API token to pull the latest rule configuration from the ruleboard in Semgrep UI.
runs:
  using: composite
  steps:
    # Step 1: Checkout the repository with shallow depth
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    # Step 2: Install Semgrep (if not already installed) and run the scan
    - run: |
        export PATH=$PATH:$HOME/.local/bin

        # Install Semgrep if not already available
        pipx install --force semgrep

        # Run Semgrep with provided token
        SEMGREP_APP_TOKEN="${{ inputs.semgrep-app-token }}" semgrep ci
      shell: bash
