name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings as comments on pull requests.

inputs:
  semgrep-app-token:
    required: true
    description: Semgrep API token to pull the latest rule configuration from the ruleboard in Semgrep UI.

runs:
  using: composite
  steps:
    - uses: open-turo/action-setup-tools@v2
      with:
        python: 3.10.12

    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Run Semgrep
      run: |
        SEMGREP_APP_TOKEN="${{ inputs.semgrep-app-token }}" pipx run --spec semgrep==1.101.0 semgrep ci
      shell: bash

    - name: Cleanup Semgrep Environment
      run: |
        echo "=== Starting Cleanup ==="

        # Remove the Semgrep cache directory if it exists
        if [ -d ~/.semgrep ]; then
          echo "Removing ~/.semgrep directory..."
          rm -rf ~/.semgrep
        else
          echo "~/.semgrep directory does not exist. Skipping..."
        fi

        # Remove pipx installation directory for Semgrep if it exists
        if [ -d ~/.local/pipx ]; then
          echo "Removing ~/.local/pipx directory..."
          rm -rf ~/.local/pipx
        else
          echo "~/.local/pipx directory does not exist. Skipping..."
        fi

        # Remove any pipx binary folder if it exists
        if [ -d ~/.local/bin ]; then
          echo "Removing Semgrep binary from ~/.local/bin..."
          find ~/.local/bin -name "semgrep*" -exec rm -f {} \;
        else
          echo "~/.local/bin directory does not exist. Skipping..."
        fi

        echo "=== Cleanup Completed ==="
      shell: bash
