name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings as comments on pull requests.
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep API token to pull the latest rule configuration from the ruleboard in Semgrep UI.
runs:
  using: composite
  steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    # Step 2: Ensure Semgrep is installed and run the scan
    - run: |
        # Ensure PATH includes ~/.local/bin for pipx-installed tools
        export PATH=$PATH:$HOME/.local/bin

        # Check if Semgrep is installed
        if ! command -v semgrep &> /dev/null; then
          echo "Semgrep not found. Installing Semgrep..."
          pipx install semgrep               # Install the latest version
        else
          echo "Semgrep already installed. Skipping installation."
        fi

        # Output Semgrep version for debugging purposes
        semgrep --version

        # Run Semgrep with the specified configuration
        SEMGREP_APP_TOKEN="${{ inputs.semgrep-app-token }}" semgrep ci --verbose
      shell: bash
