name: Run static code analysis
description: Github Action that scans code changes being made and posts security findings in form of comments on pull requests
inputs:
  checkout-repo:
    description: Perform checkout as first step
    required: false
    default: "true"
  semgrep-app-token:
    required: true
    description: SemGrep API token to be added to repo that allows to pull latest rule config from ruleboard in Semgrep UI
runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{inputs.checkout-repo == 'true'}}
      uses: actions/checkout@v4
    - name: Run semgrep
      run: |
        docker run --rm -v  "${PWD}:/src" \
        -e SEMGREP_APP_TOKEN=${{ inputs.semgrep-app-token }} \
        -e SEMGREP_REPO_NAME=${GITHUB_REPOSITORY} \
        -e SEMGREP_BRANCH=${GITHUB_REF} \
        -e SEMGREP_COMMIT=${{ github.event.pull_request.head.sha }} \
        -e SEMGREP_PR_ID=${{github.event.pull_request.number}} \
        returntocorp/semgrep:latest-nonroot \
        semgrep ci
      shell: bash
