name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings as comments on pull requests.
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep API token to pull the latest rule configuration from the ruleboard in Semgrep UI.
  config:
    required: false
    default: ""
    description: Optional Semgrep config name (e.g., p/secrets)
runs:
  using: composite
  steps:
    - uses: open-turo/action-setup-tools@v2
      with:
        python: 3.13.2

    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - run: |
        echo "Debug PATH information:"
        echo $PATH
        python --version
        which pipx || echo "pipx not found"
        if [ -n "${{ inputs.config }}" ]; then
          SEMGREP_APP_TOKEN="${{ inputs.semgrep-app-token }}" \
            pipx run --spec semgrep==1.101.0 semgrep ci --config "${{ inputs.config }}"
        else
          SEMGREP_APP_TOKEN="${{ inputs.semgrep-app-token }}" \
            pipx run --spec semgrep==1.101.0 semgrep ci
        fi
      shell: bash
