name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings as comments on pull requests.
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep API token to pull the latest rule configuration from the ruleboard in Semgrep UI.
  scan-mode:
    required: false
    default: "ci"
    description: 'Scan mode: "ci" for context-aware scanning (default), "scan" for full repository scans'
runs:
  using: composite
  steps:
    - uses: open-turo/action-setup-tools@v3
      with:
        python: 3.13.2

    - uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.base.sha || github.ref }}
        fetch-depth: 2

    - run: |
        echo "Debug PATH information:"
        echo $PATH
        python --version
        which pipx || echo "pipx not found"

        echo "🔍 Scan mode: $SCAN_MODE"

        if [ "$SCAN_MODE" = "scan" ]; then
          echo "🔍 Running full repository scan (semgrep scan --config auto)"
          SEMGREP_APP_TOKEN="$SEMGREP_APP_TOKEN" pipx run --spec semgrep==1.101.0 semgrep scan --config auto
        else
          echo "🔍 Running context-aware scan (semgrep ci - auto-detects PR vs full based on environment)"
          SEMGREP_APP_TOKEN="$SEMGREP_APP_TOKEN" pipx run --spec semgrep==1.101.0 semgrep ci
        fi
      env:
        SCAN_MODE: ${{ inputs.scan-mode }}
        SEMGREP_APP_TOKEN: ${{ inputs.semgrep-app-token }}
      shell: bash
