name: Run Semgrep via explicit docker call
description: Run Semgrep via explicit docker call
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep app token
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - run: |
        pipx install semgrep
        SEMGREP_APP_TOKEN="${{ inputs.semgrep-app-token }}" semgrep ci
      shell: bash
