name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings as comments on pull requests.
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep API token to pull the latest rule configuration from the ruleboard in Semgrep UI.
runs:
  using: composite
  steps:
    - uses: open-turo/action-setup-tools/versions@v2
      with:
        python: 3.12.0

    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - run: |
        export PATH=$PATH:$HOME/.local/bin

        pipx install --force semgrep  # Install Semgrep if not already available

        SEMGREP_APP_TOKEN="${{ inputs.semgrep-app-token }}" semgrep ci
      shell: bash
