#name: Build semgrep container
#description: GitHub Action that builds semgrep container using returntocorp/semgrep image and passses semgrep command as args
#inputs:
#  semgrep-app-token:
#    required: true
#    description: SemGrep API token to be added to repo that allows to pull latest rule config from ruleboard in Semgrep UI
#runs:
#  using: docker
#  image: docker://returntocorp/semgrep
#  args:
#    - semgrep
#    - ci
#  env:
#    SEMGREP_APP_TOKEN: ${{ inputs.semgrep-app-token }}

# TODO: remove after Semgrep has addressed the issue with files being created using root user on github runners causing other actions on same github runner to fail.

name: Run static code analysis
description: Github Action that scans code changes being made and posts security findings in form of comments on pull requests
inputs:
  checkout-repo:
    description: Perform checkout as first step
    required: false
    default: "true"
  semgrep-app-token:
    required: true
    description: SemGrep API token to be added to repo that allows to pull latest rule config from ruleboard in Semgrep UI
runs:
  using: composite
  steps:
    - run: echo "pausing checks"
      shell: bash
#    - name: Checkout
#      if: ${{inputs.checkout-repo == 'true'}}
#      uses: actions/checkout@v3
#    - name: Run semgrep
#      uses: ${GITHUB_ACTION_PATH}/static-analysis/semgrep
#      with:
#        semgrep-app-token: ${{ inputs.semgrep-app-token }}
