name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings in the form of comments on pull requests
inputs:
  checkout-repo:
    description: Perform checkout as the first step
    required: false
    default: "true"
  semgrep-app-token:
    required: true
    description: Semgrep API token to be added to the repo that allows pulling the latest rule config from the ruleboard in the Semgrep UI
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'

runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{ inputs.checkout-repo == 'true' }}
      uses: actions/checkout@v4

    # Step to determine the default branch dynamically
    - name: Get default branch
      id: default-branch
      run: |
        default_branch=$(gh api repos/${{ github.repository }} --jq .default_branch)
        echo "Default branch is $default_branch"
        echo "default_branch=$default_branch" >> $GITHUB_ENV
      env:
        github-token: ${{ inputs.github-token}}
      shell: bash

    # Semgrep CI step with dynamic baseline reference
    - run: |
        docker run --rm -v "${PWD}:/src" \
        -e SEMGREP_APP_TOKEN=${{ inputs.semgrep-app-token }} \
        -e SEMGREP_REPO_NAME=${GITHUB_REPOSITORY} \
        -e SEMGREP_BRANCH=${GITHUB_REF} \
        -e SEMGREP_COMMIT=${{ github.event.pull_request.head.sha }} \
        -e SEMGREP_BASELINE_REF=refs/remotes/origin/${{ env.default_branch }} \
        -e SEMGREP_PR_ID=${{ github.event.pull_request.number }} \
        returntocorp/semgrep:latest-nonroot \
        semgrep ci
      shell: bash
