name: Run static code analysis
description: GitHub Action that scans code changes being made and posts security findings in form of comments on pull requests
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep API token to pull the latest rule configuration from Semgrep's ruleboard
  checkout-repo:
    description: Perform checkout as the first step
    required: false
    default: "true"

runs:
  using: docker
  image: docker://semgrep/semgrep:latest-nonroot
  entrypoint: semgrep
  args:
    - ci
