name: "Security Scan Composite Action"
description: >
  GitHub Action for scanning container images for vulnerabilities using Lacework.

inputs:
  dockerhub-user:
    required: false
    default: ""
    description: DockerHub username
  dockerhub-password:
    required: false
    default: ""
    description: DockerHub password
  image-name:
    required: false
    description: Docker image name
  image-tag:
    required: true
    description: Docker image tag
  enable-docker-build:
    required: false
    default: true
    description: Enable Docker build
  lw-account-name:
    required: true
    description: Lacework account name
  lw-access-token:
    required: true
    description: Lacework access token
  github-token:
    required: true
    description: GitHub token
  build-args:
    required: false
    description: Docker build arguments
  output-format:
    required: false
    default: "json"
    description: "Output format for Lacework scan results (json/table)"

outputs:
  image-name:
    description: Name of the scanned Docker image.

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      if: ${{ inputs.enable-docker-build }}
      uses: open-turo/actions-security/docker-build@v2
      id: docker-build
      with:
        dockerhub-user: ${{ inputs.dockerhub-user }}
        dockerhub-password: ${{ inputs.dockerhub-password }}
        image-version: ${{ inputs.image-tag }}
        load: true
        push: false
        build-args: ${{ inputs.build-args }}

    - name: Determine Image Name
      run: |
        if [ "${{ inputs.enable-docker-build }}" = "true" ]; then
          echo "IMAGE_NAME=${{ steps.docker-build.outputs.image-name }}" >> $GITHUB_ENV
        else
          echo "IMAGE_NAME=${{ inputs.image-name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Scan Container Image
      uses: lacework/lw-scanner-action@v1.4.3
      with:
        LW_ACCOUNT_NAME: ${{ inputs.lw-account-name }}
        LW_ACCESS_TOKEN: ${{ inputs.lw-access-token }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        SAVE_RESULTS_IN_LACEWORK: true
        OUTPUT_FORMAT: ${{ inputs.output-format }}

    - name: Cleanup Docker Image
      if: always()
      run: |
        echo "Cleaning up image: ${{ env.IMAGE_NAME }}:${{ inputs.image-tag }}"
        docker image rm ${{ env.IMAGE_NAME }}:${{ inputs.image-tag }}
      shell: bash
