name: Container Security Scan
description: Scans container images for vulnerabilities using Lacework

inputs:
  image-name:
    required: false
    description: Docker image name
  image-tag:
    required: true
    description: Docker image tag
  enable-docker-build:
    required: false
    default: "true"
    description: Enable Docker build
  build-args:
    required: false
    description: List of build arguments for docker build as key-value pairs
  docker-config-file:
    required: false
    description: Path to the docker config file (defaults to .docker-config.json) Must contain imageName, may contain dockerfile
    default: .docker-config.json
  secrets:
    required: false
    description: List of secrets for docker build as key-value pairs (e.g., SECRET_KEY=VALUE)
  lw-account-name:
    required: true
    description: Lacework account name
  lw-access-token:
    required: true
    description: Lacework access token
  dockerhub-user:
    required: true
    description: DockerHub username
  dockerhub-password:
    required: true
    description: DockerHub password

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build docker image
      if: ${{ inputs.enable-docker-build == 'true' }}
      uses: open-turo/actions-security/docker-build@v3
      id: docker-build
      with:
        docker-config-file: ${{ inputs.docker-config-file }}
        secrets: ${{ inputs.secrets }}
        dockerhub-user: ${{ inputs.dockerhub-user }}
        dockerhub-password: ${{ inputs.dockerhub-password }}
        image-version: ${{ inputs.image-tag }}
        build-args: ${{ inputs.build-args }}

    - name: Determine Image Name
      id: set_image_name
      run: |
        echo "image_name=${{ steps.docker-build.outputs.image-name }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Scan Container Image
      id: scan
      uses: lacework/lw-scanner-action@v1.4.3
      with:
        LW_ACCOUNT_NAME: ${{ inputs.lw-account-name }}
        LW_ACCESS_TOKEN: ${{ inputs.lw-access-token }}
        IMAGE_NAME: ${{ steps.set_image_name.outputs.image_name }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        SAVE_RESULTS_IN_LACEWORK: true
        ADDITIONAL_PARAMETERS: "-j"

    - name: Cleanup Docker Image
      if: always()
      run: |
        docker image rm ${{ steps.docker-build.outputs.image-name }}:${{ inputs.image-tag }} || true
      shell: bash
