name: Container Security Scan
description: Scans container images for vulnerabilities using Lacework

inputs:
  image-name:
    required: false
    description: Docker image name
  image-tag:
    required: true
    description: Docker image tag
  image-platform:
    description: Target platform to build image for (eg. linux/amd64 (default), linux/arm64, etc)
  enable-docker-build:
    required: false
    default: "true"
    description: Enable Docker build
  image-tags:
    required: false
    description: List of tags as key-value pair attributes
    default: ""
  artifactory-username:
    required: false
    description: Artifactory username
  artifactory-auth-token:
    required: false
    description: Artifactory auth token
  build-args:
    required: false
    description: List of build arguments for docker build as key-value pairs
  build-contexts:
    required: false
    description: List of additional build contexts (e.g., name=path)
    default: ""
  docker-config-file:
    required: false
    description: Path to the docker config file (defaults to .docker-config.json) Must contain imageName, may contain dockerfile
    default: .docker-config.json
  github-token:
    required: false
    description: GitHub token
  secrets:
    required: false
    description: List of secrets for docker build as key-value pairs (e.g., SECRET_KEY=VALUE)
  lw-account-name:
    required: true
    description: Lacework account name
  lw-access-token:
    required: true
    description: Lacework access token
  dockerhub-user:
    required: true
    description: DockerHub username
  dockerhub-password:
    required: true
    description: DockerHub password
  MAX_MIND_USER:
    required: false
    description: MaxMind User ID
  MAX_MIND_LICENSE_KEY:
    required: false
    description: MaxMind License Key
  vfunction-file:
    required: false
    description: Vfunction file name
  target:
    required: false
    description: Target build stage for multi-stage Docker builds

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build docker image
      if: ${{ inputs.enable-docker-build == 'true' }}
      uses: open-turo/actions-security/docker-build@f/build-contexts
      id: docker-build
      with:
        docker-config-file: ${{ inputs.docker-config-file }}
        dockerhub-user: ${{ inputs.dockerhub-user }}
        dockerhub-password: ${{ inputs.dockerhub-password }}
        github-token: ${{ inputs.github-token }}
        image-platform: ${{ inputs.image-platform }}
        image-version: ${{ inputs.image-tag }}
        build-args: |
          ARTIFACTORY_USERNAME=${{ inputs.artifactory-username }}
          ARTIFACTORY_AUTH_TOKEN=${{ inputs.artifactory-auth-token }}
          MAX_MIND_LICENSE_KEY=${{ inputs.MAX_MIND_LICENSE_KEY }}
          ${{ inputs.build-args }}
        secrets: ${{ inputs.secrets }}
        build-contexts: ${{ inputs.build-contexts }}
    - name: Determine Image Name
      id: set_image_name
      run: |
        echo "image_name=${{ steps.docker-build.outputs.image-name }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Scan Container Image
      id: scan
      uses: lacework/lw-scanner-action@v1.4.4
      with:
        LW_ACCOUNT_NAME: ${{ inputs.lw-account-name }}
        LW_ACCESS_TOKEN: ${{ inputs.lw-access-token }}
        IMAGE_NAME: ${{ steps.set_image_name.outputs.image_name }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        SAVE_RESULTS_IN_LACEWORK: true
        ADDITIONAL_PARAMETERS: "-j"

    - name: Cleanup Docker Image
      if: always()
      run: |
        docker image rm ${{ steps.docker-build.outputs.image-name }}:${{ inputs.image-tag }} || true
      shell: bash
