name: "Security Scan Composite Action"
description: "GitHub Action for scanning container images for vulnerabilities using Lacework."

inputs:
  dockerhub-user:
    required: false
    default: ""
    description: DockerHub username for authentication.
  dockerhub-password:
    required: false
    default: ""
    description: DockerHub password for authentication.
  docker-config-file:
    required: false
    description: Path to the Docker config file (default is .docker-config.json) Must contain imageName and optionally the Dockerfile path.
    default: .docker-config.json
  github-token:
    required: true
    description: GitHub token for accessing repositories.
  lw-account-name:
    required: true
    description: Lacework account name for scanning.
  lw-access-token:
    required: true
    description: Lacework access token for scanning.
  image-name:
    required: false
    description: Name of the Docker image to scan.
  image-tag:
    required: true
    description: Tag of the Docker image to scan.
  image-platform:
    required: false
    default: linux/amd64
    description: Target platform for Docker image (e.g., linux/amd64, linux/arm64).
  build-args:
    required: false
    description: Build arguments for the Docker build as key-value pairs.
    default: ""
  secrets:
    required: false
    description: Secrets for the Docker build as key-value pairs.
    default: ""
  enable-docker-build:
    required: false
    default: true
    description: Whether to enable Docker image building (default is true).

outputs:
  image-name:
    description: Name of the scanned Docker image.
  scan-results-path:
    description: Path to the scan results file (e.g., results.stdout).

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      if: ${{ inputs.enable-docker-build }}
      uses: open-turo/actions-security/docker-build@v2
      id: docker-build
      with:
        dockerhub-user: ${{ inputs.dockerhub-user }}
        dockerhub-password: ${{ inputs.dockerhub-password }}
        github-token: ${{ inputs.github-token }}
        image-version: ${{ inputs.image-tag }}
        image-platform: ${{ inputs.image-platform }}
        load: true
        push: false
        docker-metadata-tags: |
          type=ref,event=branch
          type=ref,event=pr
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.secrets }}

    - name: Determine Image Name
      shell: bash
      id: set-image-name
      run: |
        if [ "${{ inputs.enable-docker-build }}" == "true" ]; then
          echo "::set-output name=image-name::${{ steps.docker-build.outputs.image-name }}"
        else
          echo "::set-output name=image-name::${{ inputs.image-name }}"
        fi

    - name: Scan Container Image
      uses: lacework/lw-scanner-action@v1.4.3
      id: scan
      with:
        LW_ACCOUNT_NAME: ${{ inputs.lw-account-name }}
        LW_ACCESS_TOKEN: ${{ inputs.lw-access-token }}
        IMAGE_NAME: ${{ steps.set-image-name.outputs.image-name }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        SAVE_RESULTS_IN_LACEWORK: true
        RESULTS_IN_GITHUB_SUMMARY: true

    - name: Check for Lacework Scan Results
      id: check-results
      run: |
        if [ -f results.stdout ]; then
          echo "Scan results file (results.stdout) exists."
          echo "::set-output name=scan-results-path=results.stdout" >> "$GITHUB_ENV"
        else
          echo "Scan results file (results.stdout) does not exist."
          exit 1
        fi
      shell: bash

    - name: Format Results for PR
      if: always()
      run: |
        echo "## Lacework Inline Scanner Results" > pr-results.md
        echo "<details><summary>Click to expand</summary>" >> pr-results.md
        echo "<pre>" >> pr-results.md
        cat results.stdout >> pr-results.md
        echo "</pre>" >> pr-results.md
        echo "</details>" >> pr-results.md
      shell: bash

    - name: Check for Previous Report Comment
      id: fc
      if: github.event_name == 'pull_request' && github.event.pull_request.number != ''
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "Lacework Inline Scanner Results"

    - name: Delete Previous Test Report Comment
      if: github.event_name == 'pull_request' && steps.fc.outputs.comment-id != ''
      uses: winterjung/comment@v1
      with:
        type: delete
        comment_id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ inputs.github-token }}

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: pr-results.md
        mode: recreate
        comment_tag: to_recreate
        github_token: ${{ inputs.github-token }}

    - name: Cleanup Docker Image
      if: always()
      run: |
        echo "Image Name: ${{ steps.docker-build.outputs.image-name }}"
        echo "Image Tag: ${{ inputs.image-tag }}"
        docker image rm ${{ steps.docker-build.outputs.image-name }}:${{ inputs.image-tag }}
      shell: bash
