name: CI

on:
  pull_request:
    branches: [main]
env:
  BRANCH_NAME: ${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v1
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  #test semgrep action working
  action:
    name: Test / Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-turo/actions-security/static-analysis/semgrep@f/add-semgrep-gha
        with:
          semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
