name: Security scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.TURO_GITHUB_WORKFLOWS_APP_ID }}
          private-key: ${{ secrets.TURO_GITHUB_WORKFLOWS_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: open-turo/actions-security/static-analysis@v4
        with:
          semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
          # Uses default "ci" mode for context-aware scanning:
          # - Differential scans for pull requests
          # - Full scans for main branch pushes
          # - Can override with scan-mode: "scan" for explicit full scans
