name: Security scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-security/static-analysis@v4
        with:
          semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
          # Uses default "ci" mode for context-aware scanning:
          # - Differential scans for pull requests
          # - Full scans for main branch pushes
          # - Can override with scan-mode: "scan" for explicit full scans
